export const defaultEnvVariables = `APP=app-mento
#APP=governance
#APP=squid-router
ENV=prod
#ENV=qa

SEED_PHRASE=""
WALLET_PASSWORD=""
IS_MAINNET=
#IS_FORK=true

SPECS_TYPE=web
SPECS_REGEX=connect-wallet
#SPECS_DIR=amount-validations

#GOVERNANCE_TESTNET_API_KEY=
#GOVERNANCE_TESTNET_API_URL=
#GOVERNANCE_MAINNET_API_KEY=
#GOVERNANCE_MAINNET_API_URL=

LOG_LEVEL=ALL
#TEST_RETRY=1
#TEST_RUNNER_TIMEOUT=
#IS_PARALLEL_RUN=true
#CUSTOM_URL=

#TESTOMAT_REPORT_GENERATION=true
#TESTOMAT_API_KEY=

`;
