import { envHelper } from "@helpers/env/env.helper";
import { Token } from "./token.constants";
import { magicStrings } from "./magic-strings.constants";

const usdtToken = Token[envHelper.isMainnet ? "USD₮" : "USDT"];
export const testSuites = {
  swap: {
    // TODO: Add token selections for testnet to be able to test it there
    tokenSelections: [
      {
        token: Token.CELO,
        validTokens: [
          usdtToken,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T61ff6eca",
      },
      {
        token: Token.USDm,
        validTokens: [
          usdtToken,
          Token.CELO,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          Token.axlUSDC,
          Token.axlEUROC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [],
        id: "T4cf1f159",
      },
      {
        token: Token.EURm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.axlEUROC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [],
        id: "T55e5689d",
      },
      {
        token: Token.BRLm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T1cdcec6e",
      },
      {
        token: Token.USDC,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T65b923f0",
      },
      {
        token: Token.USDT,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T1728aaf3",
        disable: {
          reason: "Unsupported token",
          chain: magicStrings.chain.mainnet.name,
        },
      },
      {
        token: Token["USD₮"],
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T1728aaf3",
        disable: {
          reason: "Unsupported token",
          chain: magicStrings.chain.testnet.name,
        },
      },
      {
        token: Token.axlUSDC,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T3842f1e6",
      },
      {
        token: Token.axlEUROC,
        validTokens: [Token.USDm, Token.EURm],
        invalidTokens: [
          Token.CELO,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        id: "T1b2d5431",
      },
      {
        token: Token.XOFm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T8b44f3ea",
      },
      {
        token: Token.KESm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Tdf1f8d60",
      },
      {
        token: Token.PHPm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Td740bfbf",
      },
      {
        token: Token.COPm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T7a80e866",
      },
      {
        token: Token.GHSm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T052ce765",
      },
      {
        token: Token.GBPm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Tb6f16c86",
      },
      {
        token: Token.ZARm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T9787390d",
      },
      {
        token: Token.CADm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T14202806",
      },
      {
        token: Token.AUDm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.CHFm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Tee27957f",
      },
      {
        token: Token.CHFm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.JPYm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Tf78b7915",
      },
      {
        token: Token.JPYm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.NGNm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Td80ddce2",
      },
      {
        token: Token.NGNm,
        validTokens: [
          Token.CELO,
          Token.USDm,
          Token.EURm,
          Token.BRLm,
          Token.USDC,
          usdtToken,
          Token.axlUSDC,
          Token.XOFm,
          Token.KESm,
          Token.PHPm,
          Token.COPm,
          Token.GHSm,
          Token.GBPm,
          Token.ZARm,
          Token.CADm,
          Token.AUDm,
          Token.CHFm,
          Token.JPYm,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T7084e96f",
      },
    ],
  },
};
