import { Token } from "./token.constants";

export const testSuites = {
  swap: {
    // TODO: Add token selections for alfajores
    tokenSelections: [
      {
        token: Token.CELO,
        validTokens: [
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T61ff6eca",
      },
      {
        token: Token.cUSD,
        validTokens: [
          Token.CELO,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.axlEUROC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [],
        id: "T4cf1f159",
      },
      {
        token: Token.cEUR,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.axlEUROC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [],
        id: "T55e5689d",
      },
      {
        token: Token.cREAL,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T1cdcec6e",
      },
      {
        token: Token.USDC,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T65b923f0",
      },
      {
        token: Token.USDT,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T1728aaf3",
      },
      {
        token: Token.axlUSDC,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T3842f1e6",
      },
      {
        token: Token.axlEUROC,
        validTokens: [Token.cUSD, Token.cEUR],
        invalidTokens: [
          Token.CELO,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        id: "T1b2d5431",
      },
      {
        token: Token.eXOF,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T8b44f3ea",
      },
      {
        token: Token.cKES,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Tdf1f8d60",
      },
      {
        token: Token.PUSO,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Td740bfbf",
      },
      {
        token: Token.cCOP,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T7a80e866",
      },
      {
        token: Token.cGHS,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T052ce765",
      },
      {
        token: Token.cGBP,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Tb6f16c86",
      },
      {
        token: Token.cZAR,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T9787390d",
      },
      {
        token: Token.cCAD,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T14202806",
      },
      {
        token: Token.cAUD,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cCHF,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Tee27957f",
      },
      {
        token: Token.cCHF,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cJPY,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Tf78b7915",
      },
      {
        token: Token.cJPY,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cNGN,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "Td80ddce2",
      },
      {
        token: Token.cNGN,
        validTokens: [
          Token.CELO,
          Token.cUSD,
          Token.cEUR,
          Token.cREAL,
          Token.USDC,
          Token.USDT,
          Token.axlUSDC,
          Token.eXOF,
          Token.cKES,
          Token.PUSO,
          Token.cCOP,
          Token.cGHS,
          Token.cGBP,
          Token.cZAR,
          Token.cCAD,
          Token.cAUD,
          Token.cCHF,
          Token.cJPY,
        ],
        invalidTokens: [Token.axlEUROC],
        id: "T7084e96f",
      },
    ],
  },
};
