# Generic workflow to build all test's workflows
name: Common Test Run

on:
  workflow_call:
    inputs:
      SPEC_NAMES:
        description: "Spec names of running tests"
        required: false
        type: string
      SPECS_TYPE:
        description: "Spec type of running tests"
        required: false
        type: string
      SPECS_FOLDER_NAME:
        description: "Spec relative folder name of running tests"
        required: false
        type: string
      IS_PARALLEL_RUN:
        description: "Parallel run flag of running tests"
        required: false
        default: "false"
        type: string
      CUSTOM_URL:
        description: "Custom base url to run tests against different URLs"
        required: false
        type: string
      IS_MAINNET:
        description: "Mainnet test run flag"
        required: false
        default: "false"
        type: string
      HTML_REPORT_NAME:
        description: "HTML report name"
        required: true
        type: string
      HTML_REPORT_GENERATION:
        description: "HTML report generation"
        required: false
        default: "onFailure"
        type: string
      TESTOMAT_REPORT_GENERATION:
        description: "Testomat test run report generation"
        required: false
        default: "true"
        type: string
      TESTOMATIO_TITLE:
        description: "Title of test run in the Testomat"
        required: false
        type: string
    secrets:
      SEED_PHRASE:
        description: "Seed phrase to import wallet"
        required: true
      WALLET_PASSWORD:
        description: "Wallet password to login to wallet"
        required: true
      TESTOMAT_API_KEY:
        description: "API key to sync with Testomat account"
        required: true

jobs:
  test:
    timeout-minutes: 60
    env:
      SPECS_TYPE: ${{ inputs.SPECS_TYPE }}
      SPEC_NAMES: ${{ inputs.SPEC_NAMES }}
      SPECS_FOLDER_NAME: ${{ inputs.SPECS_FOLDER_NAME }}
      IS_PARALLEL_RUN: ${{ inputs.IS_PARALLEL_RUN }}
      CUSTOM_URL: ${{ inputs.CUSTOM_URL }}
      IS_MAINNET: ${{ inputs.IS_MAINNET }}
      HTML_REPORT_GENERATION: ${{ inputs.HTML_REPORT_GENERATION }}
      TESTOMAT_REPORT_GENERATION: ${{ inputs.TESTOMAT_REPORT_GENERATION }}
      SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
      WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD }}
      TESTOMAT_API_KEY: ${{ secrets.TESTOMAT_API_KEY }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.2-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node install
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18.20.0

      - name: Install dependencies
        run: npm ci

      - name: Code-Check
        run: npm run codeCheck

      - name: Build Synpress cache
        run: xvfb-run npx synpress src/wallet-setups

      - name: Set current datetime
        run: |
          CURRENT_DATETIME=$(date +"%Y-%m-%d %H:%M:%S")
          echo "CURRENT_DATETIME=$CURRENT_DATETIME" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: xvfb-run npx playwright test
        env:
          TESTOMATIO_TITLE: "${{ inputs.TESTOMATIO_TITLE }} by ${{ github.actor }} at: ${{ env.CURRENT_DATETIME }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ (inputs.HTML_REPORT_GENERATION == 'true') || (failure() && inputs.HTML_REPORT_GENERATION == 'onFailure') }}
        with:
          name: "${{ inputs.HTML_REPORT_NAME }}-playwright-report"
          path: "artifacts/reports/playwright-report/"
          retention-days: 30
