name: Common Test Run

on:
  workflow_call:
    inputs:
      SPEC_NAMES:
        description: "Spec names of running tests"
        required: false
        type: string
      SPECS_TYPE:
        description: "Spec type of running tests"
        required: false
        type: string
      HTML_REPORT_GENERATION:
        description: "Flag to configure html report generation"
        required: true
        type: string
      TESTOMAT_REPORT_GENERATION:
        description: "Flag to configure testomat test run report generation"
        required: true
        type: string
      TESTOMATIO_TITLE:
        description: "Title of test run in the test management system"
        required: true
        type: string
    secrets:
      SEED_PHRASE:
        description: "Seed phrase to connect wallet"
        required: true
      TESTOMAT_API_KEY:
        description: "Testomat api key for defining test management system account"
        required: true

jobs:
  test:
    timeout-minutes: 60
    env:
      SPECS_TYPE: ${{ inputs.SPECS_TYPE }}
      SPEC_NAMES: ${{ inputs.SPEC_NAMES }}
      HTML_REPORT_GENERATION: ${{ inputs.HTML_REPORT_GENERATION }}
      TESTOMAT_REPORT_GENERATION: ${{ inputs.TESTOMAT_REPORT_GENERATION }}
      SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
      TESTOMAT_API_KEY: ${{ secrets.TESTOMAT_API_KEY }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node install
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18.20.0

      - name: Install dependencies
        run: npm ci

      - name: Set current datetime
        run: |
          $NOW=$(date +"%Y-%m-%d %H:%M:%S")
          echo "$CURRENT_DATETIME=$NOW" >> $env:GITHUB_ENV

      - name: Set job author
        run: echo "$JOB_AUTHOR=$GITHUB_ACTOR" >> $env:GITHUB_ENV

      - name: Run Playwright tests
        run: xvfb-run npx playwright test
        env:
          TESTOMATIO_TITLE: "${{ inputs.TESTOMATIO_TITLE }} by ${{ env.JOB_AUTHOR }} at: ${{ env.CURRENT_DATETIME }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ success() && inputs.HTML_REPORT_GENERATION == 'true' || success() && inputs.HTML_REPORT_GENERATION == 'onFailure' && failure() }}
        with:
          name: playwright-report
          path: artifacts/reports/playwright-report/
          retention-days: 30
