name: Common Test Run

on:
  workflow_call:
    inputs:
      SPEC_NAMES:
        description: "Spec names of running tests"
        required: false
        type: string
      SPECS_TYPE:
        description: "Spec type of running tests"
        required: false
        type: string
      REPORT_FLAG:
        description: "Flag to configure report generating"
        required: true
        type: string
    secrets:
      SEED_PHRASE:
        description: "Seed phrase to connect wallet"
        required: true

jobs:
  test:
    timeout-minutes: 60
    env:
      SPECS_TYPE: ${{ inputs.SPECS_TYPE }}
      SPEC_NAMES: ${{ inputs.SPEC_NAMES }}
      SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node install
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18.20.0

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: xvfb-run npx playwright test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.REPORT_FLAG == 'always' && always() || (inputs.REPORT_FLAG == 'success' && success()) || (inputs.REPORT_FLAG == 'failure' && failure()) }}
        with:
          name: playwright-report
          path: artifacts/reports/playwright-report/
          retention-days: 30
