# Regression via sequential and parallel modes
name: "[Governance] Regression Test Run"

on:
  schedule:
    - cron: "0 4 * * 1-5" # Monday to Friday at 4:00 AM UTC
  workflow_dispatch:
    inputs:
      CUSTOM_URL:
        description: "Custom Environment URL"
        required: false
        type: string
      HTML_REPORT_GENERATION:
        description: "Generate HTML Report"
        type: choice
        required: false
        default: "onFailure"
        options:
          - "true"
          - "false"
          - "onFailure"
      TESTOMAT_REPORT_GENERATION:
        description: "Generate Testomat Report"
        type: boolean
        required: false
        default: true
      IS_FORK:
        description: "Use Fork Mode"
        type: boolean
        required: false
        default: false

jobs:
  governance_regression_sequential:
    name: "[Governance] Sequential Regression Test Run"
    uses: ./.github/workflows/base-test.yml
    with:
      APP_NAME: "governance"
      ENV: "prod"
      SPECS_REGEX: "@regression,@sequential"
      EXCLUDE_SPECS_REGEX: "@parallel"
      IS_PARALLEL_RUN: false
      IS_MAINNET: false
      CHAIN_NAME: "Celo"
      IS_FORK: ${{ github.event_name == 'workflow_dispatch' && inputs.IS_FORK || false }}
      HTML_REPORT_GENERATION: ${{ inputs.HTML_REPORT_GENERATION || 'onFailure' }}
      HTML_REPORT_NAME: "governance-sequential-regression"
      TESTOMAT_REPORT_GENERATION: ${{ github.event_name == 'schedule' || inputs.TESTOMAT_REPORT_GENERATION }}
      TESTOMATIO_TITLE: "[Governance] Sequential-Regression"
      CUSTOM_URL: ${{ inputs.CUSTOM_URL }}
      NOTIFICATION_MESSAGE: "[Governance] Sequential-Regression"
    secrets: inherit

  governance_regression_parallel:
    name: "[Governance] Parallel Regression Test Run"
    uses: ./.github/workflows/base-test.yml
    with:
      APP_NAME: "governance"
      ENV: "prod"
      SPECS_REGEX: "@regression,@parallel"
      EXCLUDE_SPECS_REGEX: "@sequential"
      IS_PARALLEL_RUN: true
      IS_MAINNET: false
      CHAIN_NAME: "Celo"
      IS_FORK: ${{ github.event_name == 'workflow_dispatch' && inputs.IS_FORK || false }}
      HTML_REPORT_GENERATION: ${{ inputs.HTML_REPORT_GENERATION || 'onFailure' }}
      HTML_REPORT_NAME: "governance-parallel-regression"
      TESTOMAT_REPORT_GENERATION: ${{ github.event_name == 'schedule' || inputs.TESTOMAT_REPORT_GENERATION }}
      TESTOMATIO_TITLE: "[Governance] Parallel-Regression"
      CUSTOM_URL: ${{ inputs.CUSTOM_URL }}
      NOTIFICATION_MESSAGE: "[Governance] Parallel-Regression"
    secrets: inherit
