# Regression Test Run using matrix strategy to run tests sequentialy and parallelly
name: "[Governance] Regression Test Run"

on:
  schedule:
    - cron: "0 4 * * 1-5" # Monday to Friday at 4:00 AM UTC
  workflow_dispatch:
    inputs:
      HTML_REPORT_GENERATION:
        type: choice
        description: "HTML report generation"
        default: "onFailure"
        options:
          - "true"
          - "false"
          - "onFailure"
      TESTOMAT_REPORT_GENERATION:
        type: choice
        description: "Testomat test run report generation"
        default: "true"
        options:
          - "true"
          - "false"
      CUSTOM_URL:
        description: "Custom base url to run tests against different URLs"
        required: false
        type: string

jobs:
  app_mento_regression_test:
    name: "[Governance] ${{ matrix.name }} Regression Test Run"
    uses: ./.github/workflows/re-usable-test.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Sequential"
            specs_regex: "@regression,@sequential"
            exclude_specs_regex: "@parallel"
            is_parallel_run: "false"
            is_mainnet: "false"
            html_report_name: "app-mento-sequential-regression"
            testomatio_title: "[Governance] Sequential-Regression"
            notification_message: "[Governance] Sequential-Regression"
          - name: "Parallel"
            specs_regex: "@regression,@parallel"
            exclude_specs_regex: "@sequential"
            is_parallel_run: "true"
            is_mainnet: "true"
            html_report_name: "app-mento-parallel-regression"
            testomatio_title: "[Governance] Parallel-Regression"
            notification_message: "[Governance] Parallel-Regression"
    with:
      APP_NAME: "governance"
      SPECS_REGEX: ${{ matrix.specs_regex }}
      EXCLUDE_SPECS_REGEX: ${{ matrix.exclude_specs_regex }}
      IS_PARALLEL_RUN: ${{ matrix.is_parallel_run }}
      IS_MAINNET: ${{ matrix.is_mainnet }}
      HTML_REPORT_GENERATION: ${{ inputs.HTML_REPORT_GENERATION || 'onFailure' }}
      HTML_REPORT_NAME: ${{ matrix.html_report_name }}
      TESTOMAT_REPORT_GENERATION: ${{ inputs.TESTOMAT_REPORT_GENERATION || 'true' }}
      TESTOMATIO_TITLE: ${{ matrix.testomatio_title }}
      CUSTOM_URL: ${{ inputs.CUSTOM_URL }}
      NOTIFICATION_MESSAGE: ${{ matrix.notification_message }}
    secrets: inherit
