name: Manual Test Run

on:
  workflow_dispatch:
    inputs:
      SPEC_NAMES:
        description: "Spec names of running tests"
        required: true
        default: ""
      SPECS_TYPE:
        type: choice
        description: "Specs type to run exact type of tests"
        default: all
        options:
          - all
          - web
          - api

jobs:
  test:
    timeout-minutes: 60
    env:
      SPECS_TYPE: ${{ github.event.inputs.SPECS_TYPE }}
      SPEC_NAMES: ${{ github.event.inputs.SPEC_NAMES }}
      SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node install
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18.20.0

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: xvfb-run npx playwright test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
