name: Notification

on:
  workflow_call:
    # inputs:
    #   CUSTOM_URL:
    #     description: "Custom base url to run tests against different URLs"
    #     required: false
    #     type: string
    #   IS_MAINNET:
    #     description: "Mainnet test run flag"
    #     required: false
    #     default: "false"
    #     type: string
    #   TESTOMATIO_TITLE:
    #     description: "Title of test run in the Testomat"
    #     required: false
    #     type: string
    secrets:
      DISCORD_TEST_RUN_WEBHOOK_ID:
        required: true
      DISCORD_TEST_RUN_WEBHOOK_TOKEN:
        required: true

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Send Notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_TEST_RUN_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_TEST_RUN_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "Smile Notifier"
          message: "🎉 New update"
