name: PR Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: "PR Check Test Run"
    uses: ./.github/workflows/common-test.yml
    with:
      SPEC_NAMES: "connect-wallet"
      SPECS_TYPE: "web"
      IS_MAINNET: "true"
      HTML_REPORT_NAME: "pr-check-run"
      TESTOMAT_REPORT_GENERATION: "false"
      NOTIFICATION_MESSAGE: "[Mento-Web] PR Check"
    secrets: inherit
