name: PR Healthcheck

on: push

jobs:
  define-specs:
    name: "Define Specs Regex for PR Healthcheck"
    runs-on: ubuntu-latest
    outputs:
      specs-regex: ${{ steps.extract-specs-regex.outputs.specs-regex }}
    steps:
      - name: Define specs regex for PR healthcheck
        id: extract-specs-regex
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ __@regression__ ]]; then
            echo "Using the @regression tag to run regression tests"
            echo "specs-regex=@regression" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.head_commit.message }}" =~ __@full__ ]]; then
            echo "Using the @full tag to run all the tests"
            echo "specs-regex=.*" >> $GITHUB_OUTPUT  
          elif [[ "${{ github.event.head_commit.message }}" =~ __([^_]+)__ ]]; then
            echo "Using the parsed specs regex to run specific tests: ${BASH_REMATCH[1]}"
            echo "specs-regex=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "No specs regex found in commit message!"
            echo "Using the default 'connect-wallet' spec to validate the PR"
            echo "specs-regex=connect-wallet" >> $GITHUB_OUTPUT
          fi

  test:
    name: "PR Healthcheck Test Run"
    needs: define-specs
    uses: ./.github/workflows/common-test.yml
    with:
      SPECS_REGEX: ${{ needs.define-specs.outputs.specs-regex }}
      IS_MAINNET: "false"
      HTML_REPORT_NAME: "pr-healthcheck"
      TESTOMAT_REPORT_GENERATION: "false"
      NOTIFICATION_MESSAGE: "[Automated-Tests] PR Healthcheck"
    secrets: inherit
