name: Regression Test Run

on:
  schedule:
    - cron: "0 4 * * *" # Every night at 4:00 AM UTC
  workflow_dispatch: {}

jobs:
  test:
    name: "Regression Test Run"
    uses: ./.github/workflows/common-test.yml
    with:
      SPEC_NAMES: ${{ github.event.inputs.SPEC_NAMES }}
      SPECS_TYPE: ${{ github.event.inputs.SPECS_TYPE }}
      REPORT_FLAG: ${{ 'failure' }}
    secrets:
      SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
