name: Regression Test Run

on:
  schedule:
    - cron: "0 4 * * 1-5" # Monday to Friday at 4:00 AM UTC
  workflow_dispatch:
    inputs:
      HTML_REPORT_GENERATION:
        type: choice
        description: "HTML report generation"
        default: "onFailure"
        options:
          - "true"
          - "false"
          - "onFailure"
      TESTOMAT_REPORT_GENERATION:
        type: choice
        description: "Testomat test run report generation"
        default: "true"
        options:
          - "true"
          - "false"

jobs:
  test:
    name: "Regression Test Run"
    uses: ./.github/workflows/common-test.yml
    with:
      SPECS_TYPE: ${{ 'all' }}
      HTML_REPORT_GENERATION: ${{ contains(fromJSON('["true", "false", "onFailure"]'), inputs.HTML_REPORT_GENERATION) || 'onFailure' }}
      TESTOMAT_REPORT_GENERATION: ${{ contains(fromJSON('["true", "false"]'), inputs.TESTOMAT_REPORT_GENERATION) || 'true' }}
      TESTOMATIO_TITLE: "Regression"

    secrets:
      SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
      TESTOMAT_API_KEY: ${{ secrets.TESTOMAT_API_KEY }}
