name: Smoke Test Run

on:
  workflow_call:
    inputs:
      CUSTOM_URL:
        type: string
        description: "Custom base url to run tests against different URLs"
        required: true
      IS_MAINNET:
        type: string
        description: "Mainnet test run flag"
        required: false
        default: "false"
      TESTOMATIO_TITLE:
        type: string
        description: "Test run title"
        required: false
        default: "[Mento-Web] Smoke"
    secrets:
      E2E_TEST_SEED_PHRASE:
        required: true
      E2E_TEST_WALLET_PASSWORD:
        required: true
      TESTOMAT_API_KEY:
        required: true
      DISCORD_TEST_RUN_WEBHOOK_ID:
        required: true
      DISCORD_TEST_RUN_WEBHOOK_TOKEN:
        required: true
      E2E_TEST_GCP_SA_KEY:
        description: "Google Cloud Service Account key JSON"
        required: true

jobs:
  smoke-test:
    timeout-minutes: 60
    env:
      SPECS_TYPE: "web"
      SPEC_NAMES: "p1"
      IS_PARALLEL_RUN: "false"
      CUSTOM_URL: ${{ inputs.CUSTOM_URL }}
      IS_MAINNET: ${{ inputs.IS_MAINNET }}
      HTML_REPORT_NAME: "smoke-mento-web"
      HTML_REPORT_GENERATION: "onFailure"
      TESTOMAT_REPORT_GENERATION: "true"
      SEED_PHRASE: ${{ secrets.E2E_TEST_SEED_PHRASE }}
      WALLET_PASSWORD: ${{ secrets.E2E_TEST_WALLET_PASSWORD }}
      TESTOMAT_API_KEY: ${{ secrets.TESTOMAT_API_KEY }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.2-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "mento-protocol/mento-automation-tests"
          ref: "main"

      - name: Node install
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18.20.0

      - name: Install dependencies
        run: npm ci

      - name: Verify env config
        run: npm run verify-env-config

      - name: Code-Check
        run: npm run codeCheck

      - name: Build Synpress cache
        run: xvfb-run npx synpress src/wallet-setups

      - name: Set current datetime
        run: |
          CURRENT_DATETIME=$(date +"%Y-%m-%d %H:%M:%S")
          echo "CURRENT_DATETIME=$CURRENT_DATETIME" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: xvfb-run npx playwright test
        env:
          TESTOMATIO_TITLE: "${{ inputs.TESTOMATIO_TITLE }} by ${{ github.actor }} at: ${{ env.CURRENT_DATETIME }}"

      - name: Upload Playwright report
        if: ${{ (inputs.HTML_REPORT_GENERATION == 'true') || (failure() && inputs.HTML_REPORT_GENERATION == 'onFailure') }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: artifacts/reports/playwright-report/
          retention-days: 1

  report:
    needs: smoke-test
    if: ${{ (inputs.HTML_REPORT_GENERATION == 'true') || (failure() && inputs.HTML_REPORT_GENERATION == 'onFailure') }}
    uses: ./.github/workflows/report.yml
    secrets:
      GCP_SA_KEY: ${{ secrets.E2E_TEST_GCP_SA_KEY }}

  notification:
    needs: [smoke-test, report]
    if: always()
    uses: ./.github/workflows/notification.yml
    with:
      JOB_STATUS: ${{ needs.smoke-test.result }}
      MESSAGE: "[Mento-Web] Smoke by ${{ github.actor }}"
      JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      REPORT_URL: ${{ needs.report.outputs.url }}
    secrets:
      DISCORD_TEST_RUN_WEBHOOK_ID: ${{ secrets.DISCORD_TEST_RUN_WEBHOOK_ID }}
      DISCORD_TEST_RUN_WEBHOOK_TOKEN: ${{ secrets.DISCORD_TEST_RUN_WEBHOOK_TOKEN }}
