name: Smoke Test Run

on:
  workflow_call:
    inputs:
      SPEC_NAMES:
        type: string
        description: "Spec names of running test/s"
        required: true
      SPECS_FOLDER_NAME:
        type: string
        description: "Spec folder name of running test/s"
        required: false
        default: ""
      SPECS_TYPE:
        type: string
        description: "Specs type of running test/s"
        required: false
        default: "web"
      HTML_REPORT_GENERATION:
        type: string
        description: "HTML report generation"
        required: false
        default: "onFailure"
      TESTOMAT_REPORT_GENERATION:
        type: string
        description: "Testomat test run report generation"
        required: false
        default: "true"
      IS_PARALLEL_RUN:
        type: string
        description: "Parallel run flag of running tests"
        required: false
        default: "false"
      CUSTOM_URL:
        description: "Custom base url to run tests against different URLs"
        required: false
        type: string
      IS_MAINNET:
        type: string
        description: "Mainnet test run flag"
        required: false
        default: "false"

jobs:
  test:
    name: "Smoke Test Run - Mento-Web"
    uses: ./.github/workflows/common-test.yml
    with:
      SPEC_NAMES: "p1"
      SPECS_TYPE: "web"
      SPECS_FOLDER_NAME: ${{ inputs.SPECS_FOLDER_NAME }}
      HTML_REPORT_GENERATION: ${{ inputs.HTML_REPORT_GENERATION }}
      HTML_REPORT_NAME: "smoke-mento-web"
      TESTOMAT_REPORT_GENERATION: ${{ inputs.TESTOMAT_REPORT_GENERATION }}
      TESTOMATIO_TITLE: "Smoke-Mento-Web"
      IS_PARALLEL_RUN: "false"
      CUSTOM_URL: ${{ inputs.CUSTOM_URL }}
      IS_MAINNET: ${{ inputs.IS_MAINNET }}
    secrets:
      SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
      WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD }}
      TESTOMAT_API_KEY: ${{ secrets.TESTOMAT_API_KEY }}
