name: "[Squid-Router] Sequential Regression Test Run"

on:
  schedule:
    - cron: "0 6 * * 3" # Wednesday at 6:00 AM UTC
  workflow_dispatch:
    inputs:
      HTML_REPORT_GENERATION:
        type: choice
        description: "HTML report generation"
        default: "onFailure"
        options:
          - "true"
          - "false"
          - "onFailure"
      TESTOMAT_REPORT_GENERATION:
        type: choice
        description: "Testomat test run report generation"
        default: "true"
        options:
          - "true"
          - "false"

jobs:
  test:
    name: "[Squid-Router] Sequential Regression Test Run"
    uses: ./.github/workflows/re-usable-test.yml
    with:
      APP_NAME: "squid-router"
      ENV: "prod"
      SPECS_REGEX: "@regression"
      IS_PARALLEL_RUN: "false"
      IS_MAINNET: "true"
      HTML_REPORT_GENERATION: ${{ inputs.HTML_REPORT_GENERATION || 'onFailure' }}
      HTML_REPORT_NAME: "squid-router-sequential-regression"
      TESTOMAT_REPORT_GENERATION: ${{ inputs.TESTOMAT_REPORT_GENERATION || 'true' }}
      TESTOMATIO_TITLE: "[Squid-Router] Sequential-Regression"
      NOTIFICATION_MESSAGE: "[Squid-Router] Sequential-Regression"
    secrets: inherit
