name: "[Squid-Router] Regression Test Run"

on:
  schedule:
    - cron: "0 6 * * 3" # Wednesday at 6:00 AM UTC
  workflow_dispatch:
    inputs:
      HTML_REPORT_GENERATION:
        description: "Generate HTML Report"
        type: choice
        required: false
        default: "onFailure"
        options:
          - "true"
          - "false"
          - "onFailure"
      TESTOMAT_REPORT_GENERATION:
        description: "Generate Testomat Report"
        type: boolean
        required: false
        default: true

jobs:
  test:
    name: "[Squid-Router] Sequential Regression Test Run"
    uses: ./.github/workflows/base-test.yml
    with:
      APP_NAME: "squid-router"
      ENV: "prod"
      SPECS_REGEX: "@regression"
      IS_PARALLEL_RUN: false
      IS_MAINNET: true
      CHAIN_NAME: "Celo"
      IS_FORK: false
      HTML_REPORT_GENERATION: ${{ inputs.HTML_REPORT_GENERATION || 'onFailure' }}
      HTML_REPORT_NAME: "squid-router-sequential-regression"
      TESTOMAT_REPORT_GENERATION: ${{ github.event_name == 'schedule' || inputs.TESTOMAT_REPORT_GENERATION }}
      TESTOMATIO_TITLE: "[Squid-Router] Sequential-Regression"
      NOTIFICATION_MESSAGE: "[Squid-Router] Sequential-Regression"
    secrets: inherit
